version: '3'
services:
  landoop:
    image: landoop/fast-data-dev:latest
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "localhost"
      KAFKA_ADVERTISED_PORT: "9092"
    networks:
      - app-legacy
    ports:
      - "2181:2181"
      - "3030:3030"
      - "8081-8083:8081-8083"
      - "9092:9092"
      - "9581-9585:9581-9585"
  

networks:
  app-legacy:
    driver: bridge