version: '3'
services:
  lenses-dev:
    image: landoop/fast-data-dev:latest
    ports:
      - "3030:3030"
      - "2181:2181"
      - "9092:9092"
      - "9093:9093"
      - "8081:8081"
    environment:
      - SAMPLEDATA=0
      - ENABLE_SSL=1
      - KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND=true
      - LENSES_KAFKA_BROKERS=SSL://localhost:9093
      - LENSES_KAFKA_SETTINGS_CONSUMER_SECURITY_PROTOCOL=SSL
      - LENSES_KAFKA_SETTINGS_PRODUCER_SECURITY_PROTOCOL=SSL