server:
  port: 9096
spring:
  application:
      name: kafka-app
  kafka:
    topic:
       first: topic1
       second: topic2
    consumer:
      bootstrap-servers: localhost:9092
      group-id: kafka-app
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer